version: '3.7'
services:
    db:
        image: postgres:13.4
        restart: always
        user: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: test
            POSTGRES_PASSWORD: ''
            POSTGRES_HOST_AUTH_METHOD: 'trust'
        volumes:
            - ./pgdata:/var/lib/postgresql/data
            # execute sql files in specific order using #-fileName syntax when creating new DB - examples below
            # - ./src/database/initDb.sql:/docker-entrypoint-initdb.d/0-initDb.sql
            # - ./src/database/addData.sql:/docker-entrypoint-initdb.d/1-addData.sql
            # - ./src/database/addAttributes.sql:/docker-entrypoint-initdb.d/2-addAttributesdData.sql
        ports:
            - '8080:5432'
    backend:
        build: '.'
        # build: './'
        # for local development uncomment below and change ports to "3000:3000"
        # you will also need to change Dockerfile to expose 3000 and script to `npm run dev`
        # ^  npm run start instead of npm run dev? also check chokidar_usepolling = true for local react dev work
        # https://stackoverflow.com/questions/44643045/running-development-server-with-create-react-app-inside-of-a-docker-container
        volumes:
            - ./client:/app/client
            - ./client/node_modules:/app/client/node_modules
            - .:/app
            - node_modules:/app/node_modules
        links:
            - 'db'
        depends_on:
            - db
        ports:
            - '3001:3001'
            - '3000:3000'
        environment:
          DB_HOST: db
volumes:
    node_modules: