const fs = require('fs');
const path = require('path');

// This file is generated by buildspec.yml, and it contains the git hash of the current build.
const buildVersionFile = path.join(__dirname, '..', '..', '.build');

const Router = require('koa-router');
const router = new Router();

let version = 'unknown';

if (fs.existsSync(buildVersionFile)) {
    version = fs.readFileSync(buildVersionFile).toString();
}

router.get('/health', async ctx => {
    ctx.body = {
        service: 'resource',
        status: 'ok',
        version: version,
        env: process.env.NODE_ENV || 'testerrrr'
    };
});

module.exports = router;